### PR TITLE
Feature/multiclass logistic

### PR DESCRIPTION
**Pull request by wazizian**

### CODE REVIEW

**Review by floffy-f — APPROVED** [review]
LGTM ("pair-programmed")

**Comment by floffy-f** [comment]
Minor changes to fix style and cast to CPU after detach on LogReg.

**Comment by floffy-f** [comment]
Added ECOS as project dependency since CVXPY won't[1].
@iutzeler maybe we can discuss the choice of solver, to go from ECOS to some other one (Clarabel?).

[1]: See https://www.cvxpy.org/updates/index.html#cvxpy-1-6

**Comment by iutzeler** [comment]
Yup indeed, ECOS is only precised in /skwdro/solvers/specific_solvers.py  if I'm correct.

We can probably just drop the option and let the default be.

**Pull request merged**
