### PR TITLE
Following pep8 rules

### PR DESCRIPTION
**Pull request by iutzeler**
I try to make as few errors as possible under the command
``pycodestyle --statistics --ignore=E501  ./skwdro/``

(and correct some of them with ``autopep8 --in-place --aggressive file.py``

### CODE REVIEW

**Comment by iutzeler** [comment]
Next step is to check warnings with ``pyflakes``

**Comment by floffy-f** [comment]
Considering the fact that I may or may not have over-typed my part of the code, [mypy](https://mypy.readthedocs.io/en/stable/) might be an option as well.
I think this issue is rather important for the maintainability of our codebase.

**Comment by floffy-f** [comment]
(As a personnal note, I would consider replacing flake8 by [Ruff](https://github.com/astral-sh/ruff), even in my personal configs.)

**Comment by floffy-f** [comment]
*The tests now pass*, and the files show no warning through both ruff and pycodestyle.

Exceptions:
* rho tuning and its computations files.
* specific solvers file.
* All the E501 linebreaks warnings.

See `pyproject.toml` on the relevant sections.

I believe the code is now mergeable

**Pull request merged**
